import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { Loader2, Plus, Sparkles, Image as ImageIcon, CheckCircle2, FileText, Fingerprint, Calendar as CalendarIcon } from "lucide-react";
import { format } from "date-fns";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Calendar } from "@/components/ui/calendar";
import { cn } from "@/lib/utils";
import { useActiveProject } from "@/hooks/useActiveProject";

const GeneratePage = () => {
  const navigate = useNavigate();
  const { user } = useAuth();
  const { activeProjectId, activeProject } = useActiveProject();
  const projectId = activeProjectId;
  const [loading, setLoading] = useState(false);
  const [generatingTitle, setGeneratingTitle] = useState(false);

  // Form State
  const [mainKeyword, setMainKeyword] = useState("");
  const [h1, setH1] = useState("");
  const [language, setLanguage] = useState("English (US)");
  const [articleType, setArticleType] = useState("Standard Blog Post");
  const [articleSize, setArticleSize] = useState("Medium (1000-1500 words)");
  const [researchLevel, setResearchLevel] = useState("Standard AI Search");
  const [tone, setTone] = useState("None");
  const [pointOfView, setPointOfView] = useState("None");
  const [textReadability, setTextReadability] = useState("None");
  const [targetCountry, setTargetCountry] = useState("United States");

  const [icp, setIcp] = useState("");
  const [brandVoice, setBrandVoice] = useState("none");
  const [details, setDetails] = useState("");
  const [secondaryKeywords, setSecondaryKeywords] = useState("");
  const [internalLinks, setInternalLinks] = useState("");
  const [scheduledDate, setScheduledDate] = useState<Date | undefined>();
  const [externalLinks, setExternalLinks] = useState("");

  const [selectedImageFile, setSelectedImageFile] = useState<File | null>(null);

  // Structure Settings
  const [structToc, setStructToc] = useState(false);
  const [structConclusion, setStructConclusion] = useState(true);
  const [structTables, setStructTables] = useState(true);
  const [structH3, setStructH3] = useState(true);
  const [structLists, setStructLists] = useState(true);
  const [structItalics, setStructItalics] = useState(true);
  const [structQuotes, setStructQuotes] = useState(true);
  const [structKeyTakeaways, setStructKeyTakeaways] = useState(true);
  const [structFaq, setStructFaq] = useState(true);
  const [structBold, setStructBold] = useState(true);

  // Moved fetchIntegrations out since it's removed

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const effectiveProjectId = projectId || activeProjectId;
    if (!effectiveProjectId) {
      toast.error("Please select a project first.");
      return;
    }
    if (!mainKeyword || !h1) {
      toast.error("Please fill required fields (Keyword, Title)");
      return;
    }

    setLoading(true);
    try {
      // Map Article Size to word count target
      let wc = 1200;
      if (articleSize.includes("Small")) wc = 800;
      if (articleSize.includes("Medium")) wc = 1300;
      if (articleSize.includes("Large")) wc = 2200;

      let uploadedImageUrl = null;
      if (selectedImageFile) {
        const fileExt = selectedImageFile.name.split('.').pop();
        const fileName = `pregen-${Date.now()}-${Math.random()}.${fileExt}`;
        const { error: uploadError } = await supabase.storage
          .from('blog_images')
          .upload(fileName, selectedImageFile, { upsert: true });

        if (uploadError) {
          console.error("Storage upload error:", uploadError);
          throw new Error("Failed to upload image. Please ensure the 'blog_images' public storage bucket exists in Supabase.");
        }

        const { data: { publicUrl } } = supabase.storage
          .from('blog_images')
          .getPublicUrl(fileName);

        uploadedImageUrl = publicUrl;
      }

      const { data, error } = await supabase.from("content_items").insert({
        user_id: user!.id,
        project_id: effectiveProjectId,
        main_keyword: mainKeyword.trim(),
        secondary_keywords: secondaryKeywords ? secondaryKeywords.split(",").map(k => k.trim()) : [],
        word_count_target: wc,
        tone: tone !== "None" ? tone : "Professional",
        target_country: targetCountry,
        h1: h1.trim(),
        h2_list: [], // Auto-generated by backend now
        h3_list: [],
        internal_links: internalLinks ? internalLinks.split(",").map(k => k.trim()) : [],

        featured_image_url: uploadedImageUrl,
        details: details.trim() || null,
        scheduled_date: scheduledDate ? scheduledDate.toISOString() : null,
        status: "generating",
      }).select("id").single();

      if (error) throw error;

      supabase.functions.invoke("generate-blog", {
        body: {
          contentId: data.id,
          includeToc: structToc
        },
      }).catch((err: any) => console.error("Generation invoke error:", err));

      toast.success("Generation started!");
      navigate(`/app/en/content/${data.id}`);
    } catch (err: any) {
      toast.error(err.message || "Failed to start generation");
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateTitle = async () => {
    if (!mainKeyword.trim()) {
      toast.error("Please enter a Main Keyword first");
      return;
    }
    setGeneratingTitle(true);
    try {
      const { data, error } = await supabase.functions.invoke("generate-title", {
        body: { keyword: mainKeyword.trim() }
      });
      if (error) throw error;
      if (data.error) throw new Error(data.error);
      if (data.title) {
        setH1(data.title);
        toast.success("Title generated successfully");
      }
    } catch (err: any) {
      toast.error(err.message || "Failed to generate title");
    } finally {
      setGeneratingTitle(false);
    }
  };

  return (
    <div className="p-8 max-w-5xl mx-auto">
      <div className="flex items-center justify-between mb-8">
        <div>
          <h1 className="text-2xl font-black flex items-center gap-2 text-ink">
            <span className="bg-primary/10 text-primary p-2 rounded-xl">
              <FileText className="h-5 w-5" />
            </span>
            1-Click Blog Post
          </h1>
          <p className="text-ink-2 text-sm mt-1 ml-12 font-medium">Generate a high-quality article in 1 click.</p>
        </div>
        <div className="flex items-center gap-3">
          <span className="text-xs font-bold bg-pink/10 text-pink px-4 py-2 rounded-full flex items-center gap-1.5 border border-pink/20 uppercase tracking-wider">
            Cost: 1 Credit
          </span>
          <span className="text-xs font-bold bg-primary/10 text-primary px-4 py-2 rounded-full flex items-center gap-1.5 border border-primary/20 uppercase tracking-wider">
            <Sparkles className="h-4 w-4" /> 50 Credits Available
          </span>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="space-y-6">
        {/* Top Row: Keyword and Title */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 items-end">
          <div className="space-y-2">
            <Label htmlFor="keyword" className="font-semibold">Main Keyword*</Label>
            <Input
              id="keyword"
              value={mainKeyword}
              onChange={(e) => setMainKeyword(e.target.value)}
              placeholder="Enter your main keyword"
              required
              className="bg-card"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="h1" className="font-semibold">Title*</Label>
            <div className="flex gap-2">
              <Input
                id="h1"
                value={h1}
                onChange={(e) => setH1(e.target.value)}
                placeholder="Generate a title first"
                required
                className="bg-card flex-1"
              />
              <Select value={language} onValueChange={setLanguage}>
                <SelectTrigger className="w-[140px] bg-card"><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="English (US)">Eng (US)</SelectItem>
                  <SelectItem value="English (UK)">Eng (UK)</SelectItem>
                  <SelectItem value="Spanish">Spanish</SelectItem>
                  <SelectItem value="French">French</SelectItem>
                </SelectContent>
              </Select>
              <Button
                type="button"
                variant="default"
                onClick={handleGenerateTitle}
                disabled={generatingTitle || !mainKeyword.trim()}
                className="shadow-sm btn-grad text-white"
              >
                {generatingTitle ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : null}
                {generatingTitle ? "Generating..." : "Generate a Title"}
              </Button>
            </div>
          </div>
        </div>

        {/* Core Settings */}
        <div className="p-6 rounded-2xl border border-slate-200 bg-white shadow-sm shadow-slate-100 space-y-5">
          <h3 className="font-black text-lg text-slate-900 flex items-center gap-2">Core Settings</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="space-y-2">
              <Label className="text-xs font-bold uppercase tracking-wider text-slate-700">Language</Label>
              <Select value={language} onValueChange={setLanguage}>
                <SelectTrigger className="bg-white border-slate-300 font-medium"><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="English (US)">English (US)</SelectItem>
                  <SelectItem value="English (UK)">English (UK)</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label className="text-xs font-bold uppercase tracking-wider text-slate-700">Article Type</Label>
              <Select value={articleType} onValueChange={setArticleType}>
                <SelectTrigger className="bg-white border-slate-300 font-medium"><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="Standard Blog Post">Standard Blog Post</SelectItem>
                  <SelectItem value="How-to Guide">How-to Guide</SelectItem>
                  <SelectItem value="Listicle">Listicle</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label className="text-xs font-bold uppercase tracking-wider text-slate-700">Article Size</Label>
              <Select value={articleSize} onValueChange={setArticleSize}>
                <SelectTrigger className="bg-white border-slate-300 font-medium"><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="Small (500-1000 words)">Small (500-1000 words)</SelectItem>
                  <SelectItem value="Medium (1000-1500 words)">Medium (1000-1500 words)</SelectItem>
                  <SelectItem value="Large (1500-2500 words)">Large (1500-2500 words)</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label className="text-xs font-bold uppercase tracking-wider text-slate-700">Research Level</Label>
              <Select value={researchLevel} onValueChange={setResearchLevel}>
                <SelectTrigger className="bg-white border-slate-300 font-medium"><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="Standard AI Search">Standard AI Search - 1 Cr</SelectItem>
                  <SelectItem value="In-Depth Search">In-Depth Search - 2 Cr</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label className="text-xs font-bold uppercase tracking-wider text-slate-700">Tone of Voice</Label>
              <Select value={tone} onValueChange={setTone}>
                <SelectTrigger className="bg-white border-slate-300 font-medium"><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="None">None</SelectItem>
                  <SelectItem value="Professional">Professional</SelectItem>
                  <SelectItem value="Conversational">Conversational</SelectItem>
                  <SelectItem value="Authoritative">Authoritative</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label className="text-xs font-bold uppercase tracking-wider text-slate-700">Point of View</Label>
              <Select value={pointOfView} onValueChange={setPointOfView}>
                <SelectTrigger className="bg-white border-slate-300 font-medium"><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="None">None</SelectItem>
                  <SelectItem value="First Person (I/We)">First Person (I/We)</SelectItem>
                  <SelectItem value="Second Person (You)">Second Person (You)</SelectItem>
                  <SelectItem value="Third Person (They/It)">Third Person (They/It)</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label className="text-xs font-bold uppercase tracking-wider text-slate-700">Text Readability</Label>
              <Select value={textReadability} onValueChange={setTextReadability}>
                <SelectTrigger className="bg-white border-slate-300 font-medium"><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="None">None</SelectItem>
                  <SelectItem value="7th Grade">7th Grade (Simple)</SelectItem>
                  <SelectItem value="High School">High School</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label className="text-xs font-bold uppercase tracking-wider text-slate-700">Target Country</Label>
              <Select value={targetCountry} onValueChange={setTargetCountry}>
                <SelectTrigger className="bg-white border-slate-300 font-medium"><SelectValue /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="United States">United States</SelectItem>
                  <SelectItem value="United Kingdom">United Kingdom</SelectItem>
                  <SelectItem value="India">India</SelectItem>
                  <SelectItem value="Australia">Australia</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </div>

        {/* Image Settings */}
        <div className="rounded-2xl border border-slate-200 bg-white shadow-sm shadow-slate-100 overflow-hidden">
          <div className="p-5 border-b border-slate-100 bg-slate-50/50 flex flex-col sm:flex-row items-center gap-3">
            <div className="h-12 w-12 flex-shrink-0 bg-primary/10 border border-primary/20 rounded-xl flex items-center justify-center">
              <ImageIcon className="h-5 w-5 text-primary" />
            </div>
            <div>
              <h3 className="font-black text-slate-900 flex items-center gap-2 text-base">Image Settings <Badge variant="secondary" className="text-[10px] px-1.5 py-0 h-4 bg-primary/10 text-primary border border-primary/25 font-bold">BETA</Badge></h3>
              <p className="text-xs text-slate-800 font-semibold">Configure visual assets for your publication</p>
            </div>
          </div>
          <div className="p-8 text-center bg-white">
            <div className="max-w-md mx-auto space-y-3.5 text-left">
              <Label className="text-xs font-bold uppercase tracking-wider text-slate-700">Custom Featured Image <span className="font-normal text-slate-500 font-semibold">(Optional)</span></Label>
              <Input
                type="file"
                accept="image/*"
                onChange={(e) => setSelectedImageFile(e.target.files?.[0] || null)}
                className="cursor-pointer bg-white border-slate-300"
              />
              <p className="text-[11px] text-slate-600 font-medium leading-relaxed">
                Upload a custom image to be used as the featured image for the blog. If left empty, an AI image can be generated depending on your plan.
              </p>
            </div>
          </div>
        </div>

        {/* ICP */}
        <div className="space-y-2">
          <Label className="font-black flex items-center gap-2 text-slate-900">Ideal Customer Profile (ICP) <Badge variant="outline" className="text-[10px] px-1.5 py-0 h-4 text-primary border-primary bg-primary/5 font-bold">New</Badge></Label>
          <div className="flex flex-col sm:flex-row gap-4">
            <Textarea
              value={icp}
              onChange={(e) => setIcp(e.target.value)}
              placeholder="e.g., Marketing managers at B2B SaaS companies with 50-200 employees..."
              className="bg-white border-slate-300 min-h-[80px] flex-1 font-semibold"
            />
            <div className="bg-primary/5 border border-primary/20 rounded-2xl p-5 sm:w-[350px] flex items-start gap-3.5 text-xs text-slate-800 font-semibold leading-relaxed shadow-sm shadow-slate-100">
              <Fingerprint className="h-4 w-4 shrink-0 text-primary" />
              <p>Define your ideal customer profile to tailor content tone, examples, and language that resonates with your target audience.</p>
            </div>
          </div>
        </div>

        {/* Brand Voice */}
        <div className="space-y-2">
          <Label className="font-black flex items-center gap-2 text-slate-900">Brand Voice</Label>
          <div className="flex flex-col sm:flex-row gap-4 items-start">
            <Select value={brandVoice} onValueChange={setBrandVoice}>
              <SelectTrigger className="bg-white border-slate-300 w-full sm:w-[250px] font-semibold"><SelectValue placeholder="No brand kits found" /></SelectTrigger>
              <SelectContent>
                <SelectItem value="none">No brand kits found</SelectItem>
              </SelectContent>
            </Select>
            <div className="bg-primary/5 border border-primary/20 rounded-xl py-3 px-4 flex-1 flex items-center gap-2.5 text-xs text-slate-800 font-semibold leading-relaxed shadow-sm shadow-slate-100">
              <Fingerprint className="h-4 w-4 shrink-0 text-primary" />
              <p>Create unique styles and tones for different situations using Brand Voice. Select a Brand Kit to apply it directly to the content.</p>
            </div>
          </div>
          <div className="pt-2">
            <p className="text-xs font-bold text-slate-600 mb-2">* Note: You have no active Brand Kits for this workspace.</p>
            <Button variant="outline" className="h-9 text-xs font-bold border-slate-300" onClick={() => navigate('/brand-identity')}>Go to Brand Identity</Button>
          </div>
        </div>

        {/* Structure Settings */}
        <div className="p-6 rounded-2xl border border-slate-200 bg-white shadow-sm shadow-slate-100 space-y-5">
          <h3 className="font-black text-lg text-slate-900">Structure Settings</h3>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            <div className="flex flex-col gap-1.5 border-b border-slate-100 pb-2">
              <Label className="text-xs font-bold uppercase tracking-wider text-slate-700">Table of Contents</Label>
              <button type="button" onClick={() => setStructToc(!structToc)} className="flex items-center gap-2 text-sm font-bold w-full text-left text-slate-800 mt-1">
                <CheckCircle2 className={`h-4 w-4 rounded-full ${structToc ? "text-primary bg-primary/10" : "text-slate-400"}`} /> {structToc ? "Yes" : "No"}
              </button>
            </div>
            <div className="flex flex-col gap-1.5 border-b border-slate-100 pb-2">
              <Label className="text-xs font-bold uppercase tracking-wider text-slate-700">Conclusion</Label>
              <button type="button" onClick={() => setStructConclusion(!structConclusion)} className="flex items-center gap-2 text-sm font-bold w-full text-left text-slate-800 mt-1">
                <CheckCircle2 className={`h-4 w-4 rounded-full ${structConclusion ? "text-primary bg-primary/10" : "text-slate-400"}`} /> {structConclusion ? "Yes" : "No"}
              </button>
            </div>
            <div className="flex flex-col gap-1.5 border-b border-slate-100 pb-2">
              <Label className="text-xs font-bold uppercase tracking-wider text-slate-700">Tables</Label>
              <button type="button" onClick={() => setStructTables(!structTables)} className="flex items-center gap-2 text-sm font-bold w-full text-left text-slate-800 mt-1">
                <CheckCircle2 className={`h-4 w-4 rounded-full ${structTables ? "text-primary bg-primary/10" : "text-slate-400"}`} /> {structTables ? "Yes" : "No"}
              </button>
            </div>
            <div className="flex flex-col gap-1.5 border-b border-slate-100 pb-2">
              <Label className="text-xs font-bold uppercase tracking-wider text-slate-700">H3 Headings</Label>
              <button type="button" onClick={() => setStructH3(!structH3)} className="flex items-center gap-2 text-sm font-bold w-full text-left text-slate-800 mt-1">
                <CheckCircle2 className={`h-4 w-4 rounded-full ${structH3 ? "text-primary bg-primary/10" : "text-slate-400"}`} /> {structH3 ? "Yes" : "No"}
              </button>
            </div>
            <div className="flex flex-col gap-1.5 border-b border-slate-100 pb-2">
              <Label className="text-xs font-bold uppercase tracking-wider text-slate-700">Lists</Label>
              <button type="button" onClick={() => setStructLists(!structLists)} className="flex items-center gap-2 text-sm font-bold w-full text-left text-slate-800 mt-1">
                <CheckCircle2 className={`h-4 w-4 rounded-full ${structLists ? "text-primary bg-primary/10" : "text-slate-400"}`} /> {structLists ? "Yes" : "No"}
              </button>
            </div>
            <div className="flex flex-col gap-1.5 border-b border-slate-100 pb-2">
              <Label className="text-xs font-bold uppercase tracking-wider text-slate-700">Italics</Label>
              <button type="button" onClick={() => setStructItalics(!structItalics)} className="flex items-center gap-2 text-sm font-bold w-full text-left text-slate-800 mt-1">
                <CheckCircle2 className={`h-4 w-4 rounded-full ${structItalics ? "text-primary bg-primary/10" : "text-slate-400"}`} /> {structItalics ? "Yes" : "No"}
              </button>
            </div>
            <div className="flex flex-col gap-1.5 border-b border-slate-100 pb-2">
              <Label className="text-xs font-bold uppercase tracking-wider text-slate-700">Quotes</Label>
              <button type="button" onClick={() => setStructQuotes(!structQuotes)} className="flex items-center gap-2 text-sm font-bold w-full text-left text-slate-800 mt-1">
                <CheckCircle2 className={`h-4 w-4 rounded-full ${structQuotes ? "text-primary bg-primary/10" : "text-slate-400"}`} /> {structQuotes ? "Yes" : "No"}
              </button>
            </div>
            <div className="flex flex-col gap-1.5 border-b border-slate-100 pb-2">
              <Label className="text-xs font-bold uppercase tracking-wider text-slate-700">Key Takeaways</Label>
              <button type="button" onClick={() => setStructKeyTakeaways(!structKeyTakeaways)} className="flex items-center gap-2 text-sm font-bold w-full text-left text-slate-800 mt-1">
                <CheckCircle2 className={`h-4 w-4 rounded-full ${structKeyTakeaways ? "text-primary bg-primary/10" : "text-slate-400"}`} /> {structKeyTakeaways ? "Yes" : "No"}
              </button>
            </div>
            <div className="flex flex-col gap-1.5 border-b border-slate-100 pb-2">
              <Label className="text-xs font-bold uppercase tracking-wider text-slate-700">FAQ</Label>
              <button type="button" onClick={() => setStructFaq(!structFaq)} className="flex items-center gap-2 text-sm font-bold w-full text-left text-slate-800 mt-1">
                <CheckCircle2 className={`h-4 w-4 rounded-full ${structFaq ? "text-primary bg-primary/10" : "text-slate-400"}`} /> {structFaq ? "Yes" : "No"}
              </button>
            </div>
            <div className="flex flex-col gap-1.5 border-b border-slate-100 pb-2">
              <Label className="text-xs font-bold uppercase tracking-wider text-slate-700">Bold</Label>
              <button type="button" onClick={() => setStructBold(!structBold)} className="flex items-center gap-2 text-sm font-bold w-full text-left text-slate-800 mt-1">
                <CheckCircle2 className={`h-4 w-4 rounded-full ${structBold ? "text-primary bg-primary/10" : "text-slate-400"}`} /> {structBold ? "Yes" : "No"}
              </button>
            </div>
          </div>
        </div>

        {/* Details to Include */}
        <div className="space-y-2">
          <Label className="font-bold flex items-center gap-2">Details to Include <Badge variant="secondary" className="text-[10px] px-1.5 py-0 h-4 font-normal">Optional</Badge></Label>
          <p className="text-xs text-muted-foreground">What details would you like to include in your article? <span className="text-primary cursor-pointer hover:underline">Learn more</span></p>
          <Textarea
            value={details}
            onChange={(e) => setDetails(e.target.value)}
            placeholder="e.g. phone number: +1 234-567-8900"
            className="bg-card min-h-[100px]"
          />
        </div>

        {/* SEO Keywords */}
        <div className="space-y-2">
          <Label className="font-bold flex items-center gap-2">SEO Keywords <Badge variant="secondary" className="text-[10px] px-1.5 py-0 h-4 font-normal">Optional</Badge></Label>
          <p className="text-xs text-muted-foreground">Keywords to include in the text.</p>
          <Textarea
            value={secondaryKeywords}
            onChange={(e) => setSecondaryKeywords(e.target.value)}
            placeholder="Add to comma separated phrase then press Enter to add"
            className="bg-card min-h-[60px]"
          />
        </div>

        {/* Scheduled Date */}
        <div className="space-y-2">
          <Label className="font-bold flex items-center gap-2">Scheduled Date <Badge variant="secondary" className="text-[10px] px-1.5 py-0 h-4 font-normal">Optional</Badge></Label>
          <p className="text-xs text-muted-foreground">When do you want this post to be scheduled for the content calendar?</p>
          <Popover>
            <PopoverTrigger asChild>
              <Button
                variant={"outline"}
                className={cn(
                  "w-full sm:w-[280px] justify-start text-left font-normal bg-card",
                  !scheduledDate && "text-muted-foreground"
                )}
              >
                <CalendarIcon className="mr-2 h-4 w-4" />
                {scheduledDate ? format(scheduledDate, "PPP") : <span>Pick a date</span>}
              </Button>
            </PopoverTrigger>
            <PopoverContent className="w-auto p-0" align="start">
              <Calendar
                mode="single"
                selected={scheduledDate}
                onSelect={setScheduledDate}
                initialFocus
              />
            </PopoverContent>
          </Popover>
        </div>

        {/* Internal Links */}
        <div className="space-y-2">
          <Label className="font-bold flex items-center gap-2">Internal Links <Badge variant="secondary" className="text-[10px] px-1.5 py-0 h-4 font-normal">Optional</Badge></Label>
          <p className="text-xs text-muted-foreground">Provide comma-separated URLs or topics. The AI will weave these into the article automatically.</p>
          <Textarea
            value={internalLinks}
            onChange={(e) => setInternalLinks(e.target.value)}
            placeholder="https://mysite.com/about, /pricing, https://mysite.com/blog/seo"
            className="bg-card min-h-[60px]"
          />
        </div>

        {/* Bottom Bar */}
        <div className="pt-6 border-t flex flex-col items-center gap-4">
          <Badge variant="secondary" className="bg-primary/5 text-primary hover:bg-primary/10 border-0 rounded-full font-bold px-4 py-1">Estimated blog generation time: 5-10 minutes</Badge>
          <Button type="submit" className="w-[300px] btn-grad h-14 text-lg" disabled={loading}>
            {loading ? (
              <Loader2 className="mr-2 h-4 w-4 animate-spin" />
            ) : null}
            Generate Blog Post
          </Button>
        </div>
      </form>
    </div>
  );
};

export default GeneratePage;
